import 'package:flutter/material.dart';
import 'package:google_sign_in/google_sign_in.dart';
import 'package:http/http.dart' as http;
import 'dart:convert';
import 'package:spotfinder/Services/SignInService.dart';
import 'package:dio/dio.dart';
import 'dart:math';

late SignInService _signInService;


class RegisterGoogleScreen extends StatefulWidget {
  final VoidCallback onRegistrationComplete;
  GoogleSignInAccount? currentUser;

  RegisterGoogleScreen({required this.onRegistrationComplete, required this.currentUser});

  @override
  _RegisterGoogleScreenState createState() => _RegisterGoogleScreenState();
}

class _RegisterGoogleScreenState extends State<RegisterGoogleScreen> {
  final _formKey = GlobalKey<FormState>();
  final _nameController = TextEditingController();
  final _emailController = TextEditingController();
  String _autoGeneratedPassword = '';
  final _phoneController = TextEditingController();
  final _birthdayController = TextEditingController();
  final _imageController = TextEditingController();
  String _gender = 'Male';
  final Dio dio = Dio();

// Función para generar una contraseña aleatoria
  String generateRandomPassword({int length = 8}) {
    const charset =
        'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
    Random random = Random();
    return List.generate(
        length, (index) => charset[random.nextInt(charset.length)]).join();
  }

  // Función para enviar datos al backend usando dio
  Future<void> sendDataToBackend() async {
    final String baseUrl = _signInService.baseUrl; // Reemplaza con tu URL base

    try {
      // Construir el cuerpo de la solicitud
      var requestData = {
        'name': _nameController.text,
        'email': _emailController.text,
        'password':
            _autoGeneratedPassword, // Aquí puedes generar una contraseña aleatoria si es necesario
        'phone_number': _phoneController.text,
        'gender': _gender,
        'birthday': _birthdayController.text,
        'image': _imageController,
        // Otros campos según sea necesario
      };

      // Realizar la solicitud POST al backend usando dio

      final response = await dio.post(
        '$baseUrl/user/Google',
        data: requestData,
        options: Options(
          headers: {
            'Content-Type': 'application/json',
            // Puedes añadir otros headers según sea necesario
          },
        ),
      );

      if (response.statusCode == 201) {
        var responseData = response.data;
        print('User created successfully: $responseData');
        // Llamar a la función de callback para indicar que el registro fue exitoso
        widget.onRegistrationComplete();
      } else {
        var errorMessage = 'Failed to create user: ${response.statusCode}';
        print(errorMessage);
        throw Exception(errorMessage);
      }
    } catch (e) {
      print('Error creating user: $e');
      // Mostrar un mensaje de error al usuario si es necesario
      // Implementar manejo de errores según tus requerimientos
    }
  }

  Future<void> _selectDate(BuildContext context) async {
    final DateTime? picked = await showDatePicker(
      context: context,
      initialDate: DateTime.now(),
      firstDate: DateTime(1900),
      lastDate: DateTime(2100),
    );
    if (picked != null && picked != DateTime.now())
      setState(() {
        _birthdayController.text = "${picked.toLocal()}".split(' ')[0];
      });
  }

  @override
  void initState() {
    super.initState();
    // Puedes inicializar los campos de nombre y email con los datos del usuario de Google Sign-In
    _nameController.text = widget.currentUser?.displayName ?? '';
    _emailController.text = widget.currentUser?.email ?? '';
    _imageController.text = widget.currentUser?.photoUrl ?? '';
    _autoGeneratedPassword = generateRandomPassword();
  }

  @override
  Widget build(BuildContext context) {
    return AlertDialog(
      title: Text('User do not Sign Up'),
      content: Form(
        key: _formKey,
        child: SingleChildScrollView(
          child: Column(
            children: <Widget>[
              TextFormField(
                controller: _nameController,
                decoration: InputDecoration(labelText: 'Name'),
                validator: (value) {
                  if (value == null || value.isEmpty) {
                    return 'Please, fill in your name';
                  }
                  return null;
                },
              ),
              TextFormField(
                controller: _emailController,
                decoration: InputDecoration(labelText: 'Email'),
                validator: (value) {
                  if (value == null || value.isEmpty) {
                    return 'Please, fill in your email';
                  }
                  return null;
                },
              ),
              TextFormField(
                enabled:
                    false, // Campo de contraseña deshabilitado para que no se pueda editar
                initialValue:
                    _autoGeneratedPassword, // Mostrar la contraseña generada automáticamente
                decoration: InputDecoration(labelText: 'Password'),
              ),
              TextFormField(
                controller: _phoneController,
                decoration: InputDecoration(labelText: 'Phone number'),
                validator: (value) {
                  if (value == null || value.isEmpty) {
                    return 'Please, fill in your phone number';
                  }
                  return null;
                },
              ),
              DropdownButtonFormField<String>(
                value: _gender,
                decoration: InputDecoration(labelText: 'Gender'),
                items: <String>['Male', 'Female', 'Other'].map((String value) {
                  return DropdownMenuItem<String>(
                    value: value,
                    child: Text(value),
                  );
                }).toList(),
                onChanged: (newValue) {
                  setState(() {
                    _gender = newValue!;
                  });
                },
              ),
              TextFormField(
                controller: _birthdayController,
                decoration: InputDecoration(
                  labelText: 'Birthday',
                  suffixIcon: IconButton(
                    icon: Icon(Icons.calendar_today),
                    onPressed: () => _selectDate(context),
                  ),
                ),
                readOnly: true,
                validator: (value) {
                  if (value == null || value.isEmpty) {
                    return 'Please, select the date';
                  }
                  return null;
                },
              ),
              SizedBox(height: 20),
              ElevatedButton(
                onPressed: () {
                  if (_formKey.currentState!.validate()) {
                    // Aquí puedes manejar el registro del usuario con los datos proporcionados
                    sendDataToBackend(); // Llama a la función para enviar los datos al backend
                    Navigator.of(context).pop();
                  }
                },
                child: Text('Sign Up'),
              ),
            ],
          ),
        ),
      ),
      actions: <Widget>[
        TextButton(
          child: Text('Close'),
          onPressed: () {
            Navigator.of(context).pop();
          },
        ),
      ],
    );
  }
}
